//----------------------------------------------------------------------
// This File: hmac_reference_model.svh
// Generated by: QuickUVM
// Project:  hmac_tb
// Author:   qa@example.com
// SPDX-License-Identifier: MIT
//----------------------------------------------------------------------
// Implement hmac_predictor::predict() here.
// This function receives the sampled transaction (inputs + outputs as
// driven to/from DUT) and must return a NEW transaction with the
// EXPECTED output values filled in.
//
// Edit the "prediction_logic" user section below.
//----------------------------------------------------------------------

function host_seq_item hmac_predictor::predict(host_seq_item t);
  // Declare static state variables needed between calls
  // static logic [W-1:0] ex_prev;

  host_seq_item extr = host_seq_item::type_id::create("extr");

  `uvm_info("CALC #1", t.convert2string(), UVM_FULL)

  // Copy all sampled inputs & outputs
  extr.copy(t);

  // pragma quickuvm custom prediction_logic begin
  // TODO: Replace this stub with the actual DUT prediction.
  // Example for a simple register (din → dout):
  // if (!extr.rst_n) begin
  //   extr.rdata = '0;
  //   extr.hmac_done = '0;
  //   extr.hmac_idle = '0;
  // end else begin
  //   extr.rdata = extr.addr;
  //   extr.rdata = extr.wr;
  //   extr.rdata = extr.req;
  //   extr.rdata = extr.wdata;
  //   extr.hmac_done = extr.addr;
  //   extr.hmac_done = extr.wr;
  //   extr.hmac_done = extr.req;
  //   extr.hmac_done = extr.wdata;
  //   extr.hmac_idle = extr.addr;
  //   extr.hmac_idle = extr.wr;
  //   extr.hmac_idle = extr.req;
  //   extr.hmac_idle = extr.wdata;
  // end

  // AN UNFILLED SEAM CANNOT FAIL. `extr` is a copy of what was OBSERVED, so leaving this
  // stub in place makes expected == actual for every field: the scoreboard reports
  // "N Ran / N Passed" against a DUT it never modelled. That is a green bench measuring
  // nothing, and it is the single easiest way to fool yourself with this generator.
  //
  // So the stub FAILS until you replace it. Delete this line as you write the model.
  // (If this DUT genuinely needs no data-path scoreboard, set `analysis.scoreboards: []`
  // rather than leaving the seam empty — see examples/fifo.)
  `uvm_fatal("UNFILLED_PREDICTOR",
             {"the `prediction_logic` seam is still the generated stub, so `extr` is just ",
              "a copy of what was observed and every compare would trivially pass. Model ",
              "the DUT here, or set `analysis.scoreboards: []` if it needs no data-path ",
              "scoreboard."})
  // pragma quickuvm custom prediction_logic end

  `uvm_info("CALC #2", extr.convert2string(), UVM_FULL)
  return(extr);
endfunction
