//----------------------------------------------------------------------
// This File: hmac_vector_seq.svh
// Generated by: QuickUVM
// Project:  hmac_tb
// Author:   qa@example.com
// SPDX-License-Identifier: MIT
//----------------------------------------------------------------------
// S2 library sequence — kind 'directed' for agent 'host'.

class hmac_vector_seq extends uvm_sequence #(host_seq_item);
  `uvm_object_utils(hmac_vector_seq)

  // pragma quickuvm custom class_item_additional begin
  // pragma quickuvm custom class_item_additional end

  function new (string name = "hmac_vector_seq");
    super.new(name);
  endfunction

  // Item count — a test may override it via `sequence: {... count: N}` (S2).
  int unsigned count = 100;

  // 'directed' sequence — write the body below. The default skeleton
  // drives `count` randomized item(s); replace it with the
  // directed stimulus.
  task body;
    host_seq_item tr = host_seq_item::type_id::create("tr");
    `uvm_info("body", "hmac_vector_seq (directed): starting", UVM_FULL)
    // pragma quickuvm custom body begin
    repeat(count) begin
      start_item(tr);
      if (!(tr.randomize()))
        `uvm_fatal("HMAC_VECTOR_SEQ", "hmac_vector_seq randomization failed")
      finish_item(tr);
    end
    // pragma quickuvm custom body end
  endtask

endclass
