//----------------------------------------------------------------------
// This File: hmac_env.svh
// Generated by: QuickUVM
// Project:  hmac_tb
// Author:   qa@example.com
// SPDX-License-Identifier: MIT
//----------------------------------------------------------------------

class hmac_env extends uvm_env;
  `uvm_component_utils(hmac_env)

  // Agent handles
  host_agent  host_agnt;

  // Scoreboards
  hmac_scoreboard sb;

  // Functional coverage (per agent)
  host_cov host_cov_h;

  // Environment configuration
  hmac_env_cfg env_cfg;

  // pragma quickuvm custom class_item_additional begin
  // pragma quickuvm custom class_item_additional end

  function new (string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(hmac_env_cfg)::get(this, "", "env_cfg", env_cfg))
      `uvm_fatal("NOCFG", {"No hmac_env_cfg set for: ", get_full_name()})
    uvm_config_db#(host_cfg)::set(this, "host_agnt", "cfg", env_cfg.host_cfg);
    host_agnt = host_agent::type_id::create("host_agnt", this);
    sb = hmac_scoreboard::type_id::create("sb", this);
    host_cov_h = host_cov::type_id::create("host_cov_h", this);
    // pragma quickuvm custom build_phase_additional begin
    // pragma quickuvm custom build_phase_additional end
  endfunction

  function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    // Declared analysis connectivity (per analysis: block)
    host_agnt.ap.connect(sb.axp);
    host_agnt.ap.connect(host_cov_h.analysis_export);
    // pragma quickuvm custom connect_phase_additional begin
    // pragma quickuvm custom connect_phase_additional end
  endfunction

endclass
