//----------------------------------------------------------------------
// This File: host_agent.svh
// Generated by: QuickUVM
// Project:  hmac_tb
// Author:   qa@example.com
// SPDX-License-Identifier: MIT
//----------------------------------------------------------------------

class host_agent extends uvm_agent;
  `uvm_component_utils(host_agent)

  // is_active is inherited from uvm_agent; set from cfg in build_phase
  host_cfg  cfg;
  virtual host_if vif;

  uvm_analysis_port #(host_seq_item) ap;
  host_driver     drv;
  host_monitor    mon;
  host_sequencer  sqr;

  // pragma quickuvm custom class_item_additional begin
  // pragma quickuvm custom class_item_additional end

  function new (string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  virtual function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    if (!uvm_config_db#(host_cfg)::get(this, "", "cfg", cfg))
      `uvm_fatal("NOCFG", {"No host_cfg set for: ", get_full_name()})
    is_active = cfg.is_active;
    vif       = cfg.vif;
    if (is_active == UVM_ACTIVE) begin
      drv = host_driver::type_id::create("drv", this);
      sqr = host_sequencer::type_id::create("sqr", this);
    end
    mon = host_monitor::type_id::create("mon", this);
    ap  = new("ap", this);
    // pragma quickuvm custom build_phase_additional begin
    // pragma quickuvm custom build_phase_additional end
  endfunction

  virtual function void connect_phase(uvm_phase phase);
    super.connect_phase(phase);
    if (is_active == UVM_ACTIVE) begin
      drv.seq_item_port.connect(sqr.seq_item_export);
      drv.vif = vif;
    end
    mon.ap.connect(ap);
    mon.vif = vif;
    // pragma quickuvm custom connect_phase_additional begin
    // pragma quickuvm custom connect_phase_additional end
  endfunction

endclass
