//----------------------------------------------------------------------
// This File: host_seq_item.svh
// Generated by: QuickUVM
// Project:  hmac_tb
// Author:   qa@example.com
// SPDX-License-Identifier: MIT
//----------------------------------------------------------------------

class host_seq_item extends uvm_sequence_item;
  `uvm_object_utils(host_seq_item)

  // Output fields (not randomized — sampled from DUT)
       logic [31:0] rdata;
       logic hmac_done;
       logic hmac_idle;

  // Input fields (driven to DUT)
  rand bit [11:0] addr;
  rand bit wr;
  rand bit req;
  rand bit [31:0] wdata;

  // pragma quickuvm custom class_item_additional begin
  // pragma quickuvm custom class_item_additional end

  function new (string name="host_seq_item");
    super.new(name);
  endfunction

  function void do_copy(uvm_object rhs);
    host_seq_item tr;
    if(!$cast(tr, rhs)) `uvm_fatal("host_seq_item", "ILLEGAL do_copy() cast")
    super.do_copy(rhs);
    rdata = tr.rdata;
    hmac_done = tr.hmac_done;
    hmac_idle = tr.hmac_idle;
    addr = tr.addr;
    wr = tr.wr;
    req = tr.req;
    wdata = tr.wdata;

    // pragma quickuvm custom do_copy_additional begin
    // pragma quickuvm custom do_copy_additional end
  endfunction

  function bit do_compare(uvm_object rhs, uvm_comparer comparer);
    host_seq_item tr;
    bit eq;
    if(!$cast(tr, rhs)) `uvm_fatal("host_seq_item", "ILLEGAL do_compare() cast")
    eq  = super.do_compare(rhs, comparer);
    eq &= (rdata === tr.rdata);
    eq &= (hmac_done === tr.hmac_done);
    eq &= (hmac_idle === tr.hmac_idle);

    // pragma quickuvm custom do_compare_additional begin
    // pragma quickuvm custom do_compare_additional end
    return(eq);
  endfunction


  function void do_print(uvm_printer printer);
    $display("\n\n\t\t*** print()/sprint() not implemented for this transaction type ***\n\n");
  endfunction

  virtual function string input2string();
    string s = "";
    s = {s, $sformatf("addr=%0h  ", addr)};
    s = {s, $sformatf("wr=%b  ", wr)};
    s = {s, $sformatf("req=%b  ", req)};
    s = {s, $sformatf("wdata=%0h  ", wdata)};
    return(s);
  endfunction

  virtual function string output2string();
    string s = "";
    s = {s, $sformatf("rdata=%0h  ", rdata)};
    s = {s, $sformatf("hmac_done=%b  ", hmac_done)};
    s = {s, $sformatf("hmac_idle=%b  ", hmac_idle)};
    return(s);
  endfunction

  virtual function string convert2string();
    // pragma quickuvm custom convert2string_additional begin
    return({input2string(), "  ", output2string()});
    // pragma quickuvm custom convert2string_additional end
  endfunction

endclass
