//----------------------------------------------------------------------
// This File: rand_test.svh
// Generated by: QuickUVM
// Project:  hmac_tb
// Author:   qa@example.com
// SPDX-License-Identifier: MIT
//----------------------------------------------------------------------

class rand_test extends hmac_base_test;
  `uvm_component_utils(rand_test)

  function new (string name, uvm_component parent);
    super.new(name, parent);
  endfunction

  function void build_phase(uvm_phase phase);
    // pragma quickuvm custom build_phase_additional begin
    // pragma quickuvm custom build_phase_additional end
    super.build_phase(phase);
  endfunction

  task run_phase(uvm_phase phase);
    host_seq seq;
    seq = host_seq::type_id::create("seq");
    //----------------------------------------------------
    phase.raise_objection(this);
    `uvm_info("rand_test", "about to start seq", UVM_FULL)
    seq.start(e.host_agnt.sqr);
    // pragma quickuvm custom run_phase_additional begin
    // pragma quickuvm custom run_phase_additional end
    phase.drop_objection(this);
  endtask

endclass
