//----------------------------------------------------------------------
// regfile_ral_pkg — the external uvm_reg_block for the regfile DUT.
//
// In a real flow this is generated by reggen / PeakRDL / SystemRDL; here it is
// hand-written to keep the example self-contained. QuickUVM's RAL wiring (C4)
// and the C5 CSR tests consume this block by name (register_model.package /
// .block in regfile.yaml). The four 16-bit R/W registers and their reset values
// match rtl/regfile.sv.
//
// SPDX-License-Identifier: MIT
//----------------------------------------------------------------------
package regfile_ral_pkg;
  import uvm_pkg::*;
  `include "uvm_macros.svh"

  // One 16-bit R/W register; reset value + backdoor slice supplied per instance
  // before build(). `hdl_slice` is the register's HDL name RELATIVE to the block
  // root (set by the testbench, e.g. "tb_top.dut_inst"); it gives the model an
  // auto (DPI) backdoor so the uvm_reg_access_seq ("rw") test can peek/poke.
  class rw16_reg extends uvm_reg;
    rand uvm_reg_field f;
    uvm_reg_data_t reset_val = '0;
    string hdl_slice = "";
    `uvm_object_utils(rw16_reg)

    function new(string name = "rw16_reg");
      super.new(name, 16, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
      f = uvm_reg_field::type_id::create("f");
      // size, lsb, access, volatile, reset, has_reset, is_rand, indiv_access
      f.configure(this, 16, 0, "RW", 0, reset_val, 1, 1, 1);
      if (hdl_slice != "")
        add_hdl_path_slice(hdl_slice, 0, 16, 1);  // full-register backdoor slice
    endfunction
  endclass

  class regfile_reg_block extends uvm_reg_block;
    rand rw16_reg ctrl;
    rand rw16_reg cfg;
    rand rw16_reg scratch;
    rand rw16_reg status;
    `uvm_object_utils(regfile_reg_block)

    function new(string name = "regfile_reg_block");
      super.new(name, UVM_NO_COVERAGE);
    endfunction

    function rw16_reg new_reg(string name, uvm_reg_data_t reset_val,
                              uvm_reg_addr_t offset, string hdl_slice);
      rw16_reg r = rw16_reg::type_id::create(name);
      r.reset_val = reset_val;
      r.hdl_slice = hdl_slice;
      r.configure(this);
      r.build();
      default_map.add_reg(r, offset, "RW");
      return r;
    endfunction

    // build() populates the model but does NOT lock it: the caller (the generated
    // base test) owns create() -> build() -> lock_model().
    virtual function void build();
      default_map = create_map("default_map", 0, 2, UVM_LITTLE_ENDIAN);
      // hdl_slice names match rtl/regfile.sv's `regs[]` (addr[2:1] -> index).
      ctrl    = new_reg("ctrl",    16'h0000, 'h0, "regs[0]");
      cfg     = new_reg("cfg",     16'h00FF, 'h2, "regs[1]");
      scratch = new_reg("scratch", 16'hDEAD, 'h4, "regs[2]");
      status  = new_reg("status",  16'hBEEF, 'h6, "regs[3]");
    endfunction
  endclass
endpackage
