// xrun filelist — csoc QuickUVM H1 x M1 clocked-subsystem example (run from sim/)
//   xrun -f xrun.f +UVM_TESTNAME=csoc_test
// Two CLOCKED leaf blocks composed into one subsystem: acc @10ns + mul @8ns, each
// on its own clock + reset generated by the flattened tb_top (acc_clk/acc_rst_n,
// mul_clk/mul_rst_n). The parameterized clkgen is instantiated once per leaf.
-uvm
-access +rwc
-timescale 1ns/1ns
-top tb_top

+incdir+../gen

// acc leaf env layer (clocked @10ns)
../gen/a_if.sv
../gen/a_pkg.sv
../gen/acc_env_pkg.sv

// mul leaf env layer (clocked @8ns)
../gen/m_if.sv
../gen/m_pkg.sv
../gen/mul_env_pkg.sv

// top test pkg (composition classes) + clock generator
../gen/csoc_test_pkg.sv
../gen/clkgen.sv

// the real clocked DUTs (not the generated gen/*.sv stubs)
../rtl/acc.sv
../rtl/mul.sv

../gen/tb_top.sv
