//----------------------------------------------------------------------
// rvtimer_ral_pkg — the external uvm_reg_block for the rvtimer DUT.
//
// In a real flow this is generated by reggen / PeakRDL / SystemRDL; here it is
// hand-written to keep the example self-contained (faithful to QuickUVM's design:
// it consumes the reg block by name — register_model.package/.block in
// rvtimer.yaml — and delegates RAL *generation* to reggen). QuickUVM's RAL wiring
// (C4) and the C5 CSR tests consume this block by name.
//
// Four 16-bit R/W config registers (CTRL/CFG/MTIMECMP/INTR_ENABLE) + a 1-bit RO
// INTR_STATE, with backdoor HDL slices matching rtl/rvtimer.sv's named signals.
//
// SPDX-License-Identifier: MIT
//----------------------------------------------------------------------
package rvtimer_ral_pkg;
  import uvm_pkg::*;
  `include "uvm_macros.svh"

  // One register with a single field; access ("RW"/"RO"), width, reset value and a
  // backdoor slice (HDL name RELATIVE to the block root, set by the testbench to
  // "tb_top.dut_inst") are supplied per instance before build().
  class field_reg extends uvm_reg;
    rand uvm_reg_field f;
    int unsigned      fwidth    = 16;
    string            access    = "RW";
    uvm_reg_data_t    reset_val = '0;
    string            hdl_slice = "";
    `uvm_object_utils(field_reg)

    function new(string name = "field_reg");
      super.new(name, 16, UVM_NO_COVERAGE);
    endfunction

    virtual function void build();
      bit is_ro = (access == "RO");
      f = uvm_reg_field::type_id::create("f");
      // configure(parent, size, lsb, access, volatile, reset, has_reset, is_rand,
      //           individually_accessible)
      f.configure(this, fwidth, 0, access, is_ro, reset_val, 1, !is_ro, 1);
      if (hdl_slice != "")
        add_hdl_path_slice(hdl_slice, 0, fwidth, 1);
    endfunction
  endclass

  class rvtimer_reg_block extends uvm_reg_block;
    rand field_reg ctrl;
    rand field_reg cfg;
    rand field_reg mtimecmp;
    rand field_reg intr_enable;
    field_reg      intr_state;
    `uvm_object_utils(rvtimer_reg_block)

    function new(string name = "rvtimer_reg_block");
      super.new(name, UVM_NO_COVERAGE);
    endfunction

    function field_reg new_reg(string name, string access, int unsigned fwidth,
                               uvm_reg_data_t reset_val, uvm_reg_addr_t offset,
                               string hdl_slice);
      field_reg r = field_reg::type_id::create(name);
      r.access    = access;
      r.fwidth    = fwidth;
      r.reset_val = reset_val;
      r.hdl_slice = hdl_slice;
      r.configure(this);
      r.build();
      default_map.add_reg(r, offset, access);
      return r;
    endfunction

    // build() populates the model but does NOT lock it: the caller (the generated
    // base test) owns create() -> build() -> lock_model().
    virtual function void build();
      default_map = create_map("default_map", 0, 2, UVM_LITTLE_ENDIAN);
      // hdl_slice names match rtl/rvtimer.sv's register signals.
      ctrl        = new_reg("ctrl",        "RW", 16, 16'h0000, 'h0, "ctrl");
      cfg         = new_reg("cfg",         "RW", 16, 16'h0001, 'h2, "cfg");
      mtimecmp    = new_reg("mtimecmp",    "RW", 16, 16'hFFFF, 'h4, "mtimecmp");
      intr_enable = new_reg("intr_enable", "RW", 16, 16'h0000, 'h6, "inten");
      intr_state  = new_reg("intr_state",  "RO",  1, 16'h0000, 'h8, "intr_state");
      // intr_state is hardware-set RO: opt it out of the automated CSR *access* (rw)
      // test (the standard UVM mechanism; OpenTitan expresses the same exclusion via
      // csr_excl / the reggen swaccess). Otherwise uvm_reg_access_seq warns
      // "Register '...intr_state' has RO fields".
      uvm_resource_db#(bit)::set({"REG::", intr_state.get_full_name()},
                                 "NO_REG_ACCESS_TEST", 1);
    endfunction
  endclass
endpackage
